server:
  port: 9000
eureka:
  client:
    register-with-eureka: false #是否将自己注册到eureka
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:${server.port}/eureka/
spring:
  application:
    name: community-eureka
  datasource:
    #    url: jdbc:mysql://192.168.1.188:3306/community_base?characterEncoding=UTF-8&useSSL=false
    url: jdbc:mysql://127.0.0.1:3306/community_base?characterEncoding=UTF-8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root