server:
  port: 9011
spring:
  application:
   name: community-manager #指定服务名
eureka:
  client:
    serviceUrl: #Eureka客户端与Eureka服务端进行交互的地址
      defaultZone: http://127.0.0.1:9001/eureka/
  instance:
    prefer-ip-address: true
zuul:
  routes:
    community-gathering: #活动
      path: /gathering/** #配置请求URL的请求规则
      serviceId: community-gathering #指定Eureka注册中心中的服务id
    community-article: #文章
      path: /article/** #配置请求URL的请求规则
      serviceId: community-article #指定Eureka注册中心中的服务id
    community-base: #基础
      path: /base/** #配置请求URL的请求规则
      serviceId: community-base #指定Eureka注册中心中的服务id
    community-friend: #交友
      path: /friend/** #配置请求URL的请求规则
      serviceId: community-friend #指定Eureka注册中心中的服务id
    community-qa: #问答
      path: /qa/** #配置请求URL的请求规则
      serviceId: community-qa #指定Eureka注册中心中的服务id
    community-recruit: #招聘
      path: /recruit/** #配置请求URL的请求规则
      serviceId: community-recruit #指定Eureka注册中心中的服务id
    community-spit: #吐槽
      path: /spit/** #配置请求URL的请求规则
      serviceId: community-spit #指定Eureka注册中心中的服务id
    community-user: #用户
      path: /user/** #配置请求URL的请求规则
      serviceId: community-user #指定Eureka注册中心中的服务id