server:
  port: 9004
spring:
  application:
    name: community-article
  datasource:
#    url: jdbc:mysql://192.168.1.188:3306/community_base?characterEncoding=UTF-8&useSSL=false
    url: jdbc:mysql://127.0.0.1:3306/community_article?characterEncoding=UTF-8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
  jpa:
    database: mysql
    show-sql: true
    generate-ddl: true
  redis:
    host: 127.0.0.1
eureka:
  client:
    service-url:
      defaultZone : http://localhost:9000/eureka/