spring:
  application:
    name: tensquare-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/hcq0514/community-config.git
      name: base
      profile: dev
      label: master
server:
  port: 12000
